name: bukd
favicon: null
layout_spectrum: 0.28638789942488074
typography_spectrum: 0.1166991104837507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24585109180770814
  lightness: 0.4424468786455691
  saturation: 0.8449788955040276
  rhythmicContrast: 0.2730195785406977
purpose: []
